namespace SampAutobind.Enums
{
    public enum Weapons
    {
        Fist = 0,
        BrassKnuckles = 1,
        GolfClub = 2,
        Nightstick = 3,
        Knife = 4,
        BaseballBat = 5,
        Shovel = 6,
        PoolCue = 7,
        Katana = 8,
        Chainsaw = 9,
        PurpleDildo = 10,
        Dildo = 11,
        Vibrator = 12,
        SilverVibrator = 13,
        Flowers = 14,
        Cane = 15,
        Grenade = 16,
        TearGas = 17,
        MolotovCocktail = 18,
        Pistol = 22,
        SilencedPistol = 23,
        Deagle = 24,
        Shotgun = 25,
        SawnoffShotgun = 26,
        CombatShotgun = 27,
        MicroSMG = 28,
        MP5 = 29,
        AK47 = 30,
        M4 = 31,
        Tec9 = 32,
        CountryRifle = 33,
        SniperRifle = 34,
        RPG = 35,
        HSRocket = 36,
        Flamethrower = 37,
        Minigun = 38,
        SatchelCharge = 39,
        Detonator = 40,
        Spraycan = 41,
        FireExtinguisher = 42,
        Camera = 43,
        NightVisionGoggles = 44,
        ThermalGoggles = 45,
        Parachute = 46
    }
}
